import type { AidRequest, Shelter, Volunteer, Resource } from './types';

const now = Date.now();
const min = 60 * 1000;
const hr = 60 * min;

export const MOCK_REQUESTS: AidRequest[] = [
  {
    id: 'req-001',
    category: 'medical',
    priority: 'critical',
    status: 'active',
    title: 'Dialysis patient stranded near Yamuna Bank',
    details:
      'Elderly resident needs dialysis. Mayur Vihar clinic unreachable due to waterlogged roads. BP rising.',
    items: ['Dialysis transport', 'BP medication', 'Insulin (NovoRapid)'],
    contactName: 'Ramesh Verma',
    contactPhone: '+91 98xxx xx142',
    distanceMiles: 0.4,
    createdAt: now - 12 * min,
    coords: { x: 32, y: 28 },
    peopleCount: 1,
  },
  {
    id: 'req-002',
    category: 'rescue',
    priority: 'critical',
    status: 'active',
    title: 'Family trapped in flooded basement — Old Yamuna Bazar',
    details:
      'Two adults, one child. Water entered basement near Chandni Chowk. No boat access yet.',
    items: ['Boat rescue', 'Life jackets (3)', 'Drinking water'],
    contactName: 'Imran Sheikh',
    contactPhone: '+91 98xxx xx188',
    distanceMiles: 0.8,
    createdAt: now - 4 * min,
    coords: { x: 58, y: 42 },
    peopleCount: 3,
  },
  {
    id: 'req-003',
    category: 'food',
    priority: 'urgent',
    status: 'active',
    title: 'Clean water for 48 residents at Geeta Colony camp',
    details:
      '12 families sheltering at Geeta Colony community hall. Tap water contaminated by flood seepage.',
    items: ['Bottled water (20+ jerrycans)', 'Water purification tablets', 'ORS sachets'],
    contactName: 'Priya Nair',
    contactPhone: '+91 98xxx xx231',
    distanceMiles: 1.2,
    createdAt: now - 38 * min,
    coords: { x: 44, y: 62 },
    peopleCount: 48,
  },
  {
    id: 'req-004',
    category: 'shelter',
    priority: 'urgent',
    status: 'active',
    title: 'Temporary shelter for 4 children — Shakarpur',
    details:
      'Parents admitted to LNJP Hospital. Children ages 4–12 with neighbour. Need safe overnight shelter.',
    items: ['Temporary beds (4)', 'Blankets', 'Child clothing'],
    contactName: 'Sarla Devi',
    contactPhone: '+91 98xxx xx307',
    distanceMiles: 1.6,
    createdAt: now - 1.2 * hr,
    coords: { x: 70, y: 30 },
    peopleCount: 5,
  },
  {
    id: 'req-005',
    category: 'volunteers',
    priority: 'moderate',
    status: 'active',
    title: 'Sandbagging crew at Yamuna embankment — Wazirabad',
    details:
      'Embankment holding but water rising. Need 10+ volunteers for 4-hour shift. NDRF coordinating.',
    items: ['Volunteers (10+)', 'Work gloves', 'Shovels', 'Sandbags'],
    contactName: 'Havildar R. Singh (NDRF)',
    contactPhone: '+91 98xxx xx410',
    distanceMiles: 1.9,
    createdAt: now - 2 * hr,
    coords: { x: 22, y: 70 },
    peopleCount: 0,
  },
  {
    id: 'req-006',
    category: 'medical',
    priority: 'urgent',
    status: 'active',
    title: 'Oxygen concentrator for COPD patient — Seelampur',
    details:
      'Power out for 14 hours. Backup cylinder nearly empty. AIIMS trauma centre on standby for intake.',
    items: ['Oxygen concentrator', 'Portable battery pack', 'Nebulizer'],
    contactName: 'David Khanna',
    contactPhone: '+91 98xxx xx522',
    distanceMiles: 0.6,
    createdAt: now - 25 * min,
    coords: { x: 50, y: 20 },
    peopleCount: 1,
  },
  {
    id: 'req-007',
    category: 'food',
    priority: 'moderate',
    status: 'active',
    title: 'Baby formula and diapers — Usmanpur riverside',
    details:
      'Infant 4 months old. Family evacuated from Usmanpur with only essentials.',
    items: ['Formula (0–6mo)', 'Diapers (size 2)', 'Baby wipes', 'Cerelac'],
    contactName: 'Aisha Begum',
    contactPhone: '+91 98xxx xx633',
    distanceMiles: 1.1,
    createdAt: now - 55 * min,
    coords: { x: 76, y: 55 },
    peopleCount: 2,
  },
  {
    id: 'req-008',
    category: 'volunteers',
    priority: 'moderate',
    status: 'active',
    title: '4WD drivers for last-mile supply delivery — ITO',
    details:
      'Delivering supplies to cut-off colonies near ITO and Raj Ghat. Fuel reimbursed by SDM office.',
    items: ['4WD drivers (5)', 'Valid DL', 'Local route knowledge'],
    contactName: 'Linda Pinto (SDM Office)',
    contactPhone: '+91 98xxx xx744',
    distanceMiles: 1.4,
    createdAt: now - 1.5 * hr,
    coords: { x: 38, y: 48 },
    peopleCount: 0,
  },
];

export const MOCK_SHELTERS: Shelter[] = [
  {
    id: 'shelter-001',
    name: 'Rajkiya Sarvodaya Bal Vidyalaya, Mayur Vihar',
    address: 'Pocket 1, Mayur Vihar Phase I, East Delhi',
    capacity: 60,
    occupied: 45,
    coords: { x: 28, y: 50 },
    amenities: ['Pet-friendly', 'Accessible', 'Hot meals (ISKCON)', 'Medical staff'],
    status: 'open',
  },
  {
    id: 'shelter-002',
    name: 'Talkatora Indoor Stadium',
    address: 'Willingdon Crescent, New Delhi',
    capacity: 120,
    occupied: 118,
    coords: { x: 64, y: 68 },
    amenities: ['Cots provided', 'Family rooms', 'Charging station'],
    status: 'full',
  },
  {
    id: 'shelter-003',
    name: 'Ramleela Ground, Red Fort',
    address: 'Chandni Chowk, Old Delhi',
    capacity: 40,
    occupied: 12,
    coords: { x: 82, y: 38 },
    amenities: ['Hot meals (Gurudwara)', 'Quiet space', 'Counseling'],
    status: 'open',
  },
  {
    id: 'shelter-004',
    name: 'Chhatrasal Stadium',
    address: 'Model Town, North Delhi',
    capacity: 200,
    occupied: 134,
    coords: { x: 16, y: 36 },
    amenities: ['Large capacity', 'Medical staff (GTB Hospital)', 'Pet-friendly', 'Showers'],
    status: 'open',
  },
];

export const MOCK_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-001',
    name: 'Dr. Arjun R. (AIIMS, EMT)',
    skills: ['Medical', 'First aid', 'Triage'],
    coords: { x: 40, y: 35 },
    distanceMiles: 0.5,
    available: true,
  },
  {
    id: 'vol-002',
    name: 'Jenna M. (Ham Radio, Civil Defence)',
    skills: ['Comms', 'Logistics', 'Hindi/English'],
    coords: { x: 66, y: 52 },
    distanceMiles: 1.0,
    available: true,
  },
  {
    id: 'vol-003',
    name: 'Marcus T. (NDRF Reserve, 4WD)',
    skills: ['Transport', 'Heavy lifting', 'Swift-water rescue'],
    coords: { x: 30, y: 60 },
    distanceMiles: 0.7,
    available: false,
  },
];

export const EMERGENCY_ZONE = 'Yamuna Flood Relief — East Delhi NCR';

export const MOCK_RESOURCES: Resource[] = [
  {
    id: 'res-001',
    type: 'hospital',
    name: 'AIIMS Trauma Centre',
    address: 'Sri Aurobindo Marg, Ansari Nagar',
    distanceMiles: 2.1,
    coords: { x: 14, y: 80 },
    open24h: true,
    phone: '+91 11 2659 4404',
    tags: ['Emergency', 'Trauma', 'ICU', 'Dialysis'],
    status: 'open',
  },
  {
    id: 'res-002',
    type: 'hospital',
    name: 'LNJP Hospital',
    address: 'Bahadur Shah Zafar Marg, Delhi Gate',
    distanceMiles: 0.9,
    coords: { x: 42, y: 40 },
    open24h: true,
    phone: '+91 11 2323 1740',
    tags: ['Emergency', 'Pediatrics', 'Maternity'],
    status: 'limited',
  },
  {
    id: 'res-003',
    type: 'hospital',
    name: 'GTB Hospital',
    address: 'Dilshad Garden, Shahdara',
    distanceMiles: 1.7,
    coords: { x: 72, y: 22 },
    open24h: true,
    phone: '+91 11 2259 1669',
    tags: ['Emergency', 'Trauma', 'Orthopedics'],
    status: 'open',
  },
  {
    id: 'res-004',
    type: 'hospital',
    name: 'Max Super Speciality, Patparganj',
    address: '108A, IP Extension, Patparganj',
    distanceMiles: 1.3,
    coords: { x: 60, y: 28 },
    open24h: true,
    phone: '+91 11 2212 1111',
    tags: ['Emergency', 'ICU', 'Private'],
    status: 'open',
  },
  {
    id: 'res-005',
    type: 'pharmacy',
    name: 'Apollo Pharmacy, Mayur Vihar',
    address: 'Pocket 4, Mayur Vihar Phase I',
    distanceMiles: 0.5,
    coords: { x: 30, y: 52 },
    open24h: false,
    phone: '+91 11 2279 1234',
    tags: ['Insulin', 'Oxygen', 'Prescription'],
    status: 'open',
  },
  {
    id: 'res-006',
    type: 'pharmacy',
    name: 'Guardian Pharmacy, Geeta Colony',
    address: 'Main Road, Geeta Colony',
    distanceMiles: 0.8,
    coords: { x: 46, y: 64 },
    open24h: false,
    phone: '+91 11 2235 5678',
    tags: ['General', 'Baby care', 'First aid'],
    status: 'limited',
  },
  {
    id: 'res-007',
    type: 'food',
    name: 'ISKCON Food Relief Camp',
    address: 'ISKCON Temple, Sant Nagar, East of Kailash',
    distanceMiles: 1.5,
    coords: { x: 20, y: 82 },
    open24h: true,
    phone: '+91 11 2624 4400',
    tags: ['Hot meals', 'Vegetarian', 'Free'],
    status: 'open',
  },
  {
    id: 'res-008',
    type: 'food',
    name: 'Gurudwara Bangla Sahib Community Kitchen',
    address: 'Connaught Place, Baba Kharak Singh Marg',
    distanceMiles: 1.2,
    coords: { x: 52, y: 44 },
    open24h: true,
    phone: '+91 11 2584 4078',
    tags: ['Hot meals', 'Langar', 'Free', 'All welcome'],
    status: 'open',
  },
  {
    id: 'res-009',
    type: 'food',
    name: 'Delhi Govt Relief — Yamuna Pushta',
    address: 'Yamuna Pushta, Civil Lines',
    distanceMiles: 0.6,
    coords: { x: 38, y: 30 },
    open24h: false,
    phone: '1077 (Helpline)',
    tags: ['Water', 'ORS', 'Ration kit'],
    status: 'open',
  },
  {
    id: 'res-010',
    type: 'shelter',
    name: 'Rajkiya Sarvodaya Bal Vidyalaya',
    address: 'Pocket 1, Mayur Vihar Phase I',
    distanceMiles: 0.4,
    coords: { x: 28, y: 50 },
    open24h: true,
    phone: '+91 11 2275 1100',
    tags: ['Pet-friendly', 'Accessible', 'Medical staff'],
    status: 'open',
    bedsAvailable: 15,
  },
  {
    id: 'res-011',
    type: 'shelter',
    name: 'Chhatrasal Stadium',
    address: 'Model Town, North Delhi',
    distanceMiles: 1.8,
    coords: { x: 16, y: 36 },
    open24h: true,
    phone: '+91 11 2745 2200',
    tags: ['Large capacity', 'Medical staff', 'Showers'],
    status: 'open',
    bedsAvailable: 66,
  },
  {
    id: 'res-012',
    type: 'rescue',
    name: 'NDRF Command Post — Wazirabad Barrage',
    address: 'Wazirabad Barrage, Civil Lines',
    distanceMiles: 1.9,
    coords: { x: 22, y: 70 },
    open24h: true,
    phone: '011-2343 8000',
    tags: ['Boat rescue', 'Swift-water', 'Evacuation'],
    status: 'open',
  },
  {
    id: 'res-013',
    type: 'rescue',
    name: 'Civil Defence Volunteer Hub — ITO',
    address: 'ITO, Bahadur Shah Zafar Marg',
    distanceMiles: 1.0,
    coords: { x: 38, y: 48 },
    open24h: true,
    phone: '1077 (Helpline)',
    tags: ['Transport', 'Sandbagging', 'Last-mile delivery'],
    status: 'open',
  },
];
